version: '3.9'

services:
  # REST Api Image
  api:
    image: ${IMAGE_NAME}:${IMAGE_TAG}
    build:
      context: ./
      dockerfile: ./api.dockerfile
      args:
        BUILD_CONFIG: ${BUILD_CONFIG}
      cache_from:
        - type=local,src=${NUGET_CACHE_PATH},name=nuget
      secrets:
        - target: /run/secrets/nuget.config
          source: nugetconfig
          mode: 0444
  # Test Image
  test:
    image: ${TEST_IMAGE_NAME}:${IMAGE_TAG}
    build:
      context: ./
      dockerfile: ./test.dockerfile
      args:
        BUILD_CONFIG: ${BUILD_CONFIG}
        RANDOM_PROPERTY: "true"
      cache_from:
        - type=local,src=${NUGET_CACHE_PATH},name=nuget
      secrets:
        - target: /run/secrets/nuget.config
          source: nugetconfig
          mode: 0444
secrets:
  nugetconfig:
    file: ${NUGET_CONFIG_PATH}